// Faculty data - complete information for all 24 faculty members
const facultyData = [
  {
    "id": 1,
    "name": "Ms. Aashka Raval",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Aashka.Raval@sot.pdpu.ac.in",
    "photo": "images/faculty/aashkaraval.jpeg",
    "qualification": "M.Tech",
    "phdSubject": "",
    "college": "PDEU",
    "researchInterest": "",
    "phone": "81601 30780",
    "cabin": "E block 2nd floor Cubical",
    "timetable": "images/faculty/aashkatt.jpeg"
  },
  {
    "id": 2,
    "name": "Dr. Archana Nigam",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Archana.Nigam@sot.pdpu.ac.in",
    "photo": "images/faculty/archananigam.png",
    "qualification": "Ph.D, M.Tech",
    "phdSubject": "Intelligent Transportation Systems",
    "college": "DA-IICT Gandhinagar",
    "researchInterest": "Machine Learning, ITS",
    "phone": "92271 01906",
    "cabin": "Not Mentioned",
    "timetable": "images/faculty/archanatt.jpeg"
  },
  {
    "id": 3,
    "name": "Dr. Ashish Patel",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Ashish.Patel1@sot.pdpu.ac.in",
    "photo": "images/faculty/ashishpatel.jpeg",
    "qualification": "Ph.D, M.E., B.E.",
    "phdSubject": "Computer Engineering",
    "college": "PDEU",
    "researchInterest": "Smart Systems",
    "cabin": "F 205",
    "timetable": "images/faculty/ashishtt.jpeg"
  },
  {
    "id": 4,
    "name": "Dr. Azriel Henry",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Azriel.Henry_ad@sot.pdpu.ac.in",
    "photo": "images/faculty/azrielhenry.jpeg",
    "qualification": "Ph.D, M.E",
    "phdSubject": "Cyber Security",
    "college": "Institute of Advanced Research Gandhinagar",
    "researchInterest": "Cyber Security & AI",
    "phone": "88661 46303",
    "cabin": "F 305",
    "timetable": "images/faculty/azrieltt.jpeg"
  },
  {
    "id": 5,
    "name": "Mr. Bhaumik Thakkar",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Bhaumik.Thakkar@sot.pdpu.ac.in",
    "photo": "images/faculty/bhaumikthakkar.jpeg",
    "qualification": "MTech",
    "phdSubject": "",
    "college": "IIIT Bangalore",
    "researchInterest": "",
    "cabin": "Not Mentioned",
    "timetable": "images/faculty/bhaumiktt.jpeg"
  },
  {
    "id": 6,
    "name": "Dr. Davinder Paul Singh",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Davinder.Singh@sot.pdpu.ac.in",
    "photo": "images/faculty/davinderpaulsingh.jpeg",
    "qualification": "Ph.D, M.Tech",
    "phdSubject": "Computer Science & Engineering",
    "college": "Shri Mata Vaishno Devi University J&K",
    "researchInterest": "AI & ML",
    "phone": "70062 91893",
    "cabin": "E 215",
    "timetable": "images/faculty/davindertt.jpeg"
  },
  {
    "id": 7,
    "name": "Dr. Debabrata Swain",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Debabrata.Swain@sot.pdpu.ac.in",
    "photo": "images/faculty/debabrataswain.jpeg",
    "qualification": "Ph.D",
    "phdSubject": "Computer Science and Engineering",
    "college": "KIIT University",
    "researchInterest": "ML, DL & NLP",
    "phone": "94202 82817",
    "cabin": "F block 3rd floor Cubical",
    "timetable": "images/faculty/debabratatt.jpeg"
  },
  {
    "id": 8,
    "name": "Dr. Hargeet Kaur",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Hargeet.Kaur@sot.pdpu.ac.in",
    "photo": "images/faculty/hargeetkaur.jpeg",
    "qualification": "Ph.D",
    "phdSubject": "Computer Science & Engineering",
    "college": "IIT Jodhpar",
    "researchInterest": "Quantum Information & Computation",
    "phone": "70237 90523",
    "cabin": "F block 3rd floor Cubical",
    "timetable": "images/faculty/hargeettt.jpeg"
  },
  {
    "id": 9,
    "name": "Dr. Kalgi Gandhi",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Kalgi.Gandhi@sot.pdpu.ac.in",
    "photo": "images/faculty/kalgigandhi.jpeg",
    "qualification": "Ph.D",
    "phdSubject": "Distributed Databases",
    "college": "DAU Gandhinagar",
    "researchInterest": "Databases, Edge Computing",
    "phone": "79843 80204",
    "cabin": "F 105",
    "timetable": "images/faculty/kalgitt.jpeg"
  },
  {
    "id": 10,
    "name": "Dr. Kaushal Shah",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Kaushal.Shah@sot.pdpu.ac.in",
    "photo": "images/faculty/kaushalshah.jpeg",
    "qualification": "Ph.D",
    "phdSubject": "Computer Science & Engineering",
    "college": "SVNIT",
    "researchInterest": "Blockchain Technology",
    "phone": "74956 63470",
    "cabin": "F block 5th floor Cubical",
    "timetable": "images/faculty/kaushaltt.jpeg"
  },
  {
    "id": 11,
    "name": "Ms. Komal Singh",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Komal.S@sot.pdpu.ac.in",
    "photo": "images/faculty/komalsingh.jpeg",
    "qualification": "M.E",
    "phdSubject": "",
    "college": "LDRP",
    "researchInterest": "",
    "phone": "85117 05400",
    "cabin": "F 305",
    "timetable": "images/faculty/komaltt.jpeg"
  },
  {
    "id": 12,
    "name": "Dr. Manish Paliwal",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Manish.Paliwal@sot.pdpu.ac.in",
    "photo": "images/faculty/manishpaliwal.jpeg",
    "qualification": "B.E., M.Tech., Ph.D",
    "phdSubject": "Software & Distributed Networks",
    "college": "VNIT Nagpur",
    "researchInterest": "Software Defined Networks",
    "phone": "77449 35721",
    "cabin": "F block 5th floor Cubical",
    "timetable": "images/faculty/manishtt.jpeg"
  },
  {
    "id": 13,
    "name": "Dr. Nandini Modi",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Nandini.Modi@sot.pdpu.ac.in",
    "photo": "images/faculty/nandinimodi.jpeg",
    "qualification": "Ph.D, M.Tech",
    "phdSubject": "Computer Science & Engineering",
    "college": "Chitkari University",
    "researchInterest": "Eye Tracking & NLP",
    "phone": "82839 21106",
    "cabin": "F 205",
    "timetable": "images/faculty/nandinitt.jpeg"
  },
  {
    "id": 14,
    "name": "Dr. Payal Chaudhari",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Payal.Chaudhari@sot.pdpu.ac.in",
    "photo": "images/faculty/payalchaudhri.jpeg",
    "qualification": "Ph.D",
    "phdSubject": "Computer Science & Engineering",
    "college": "DA-IICT Gandhinagar",
    "researchInterest": "Information Security, IoT",
    "phone": "99091 80927",
    "cabin": "E 215",
    "timetable": "images/faculty/payaltt.jpeg"
  },
  {
    "id": 15,
    "name": "Ms. Prarthana Mehta",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Prarthana.Mehta@sot.pdpu.ac.in",
    "photo": "images/faculty/prathnamehta.jpeg",
    "qualification": "ME",
    "phdSubject": "",
    "college": "LD College of Engineering Ahmedabad",
    "researchInterest": "Smart Grid Security",
    "phone": "81607 37440",
    "cabin": "F 305",
    "timetable": "images/faculty/prarthanatt.jpeg"
  },
  {
    "id": 16,
    "name": "Dr. Punit Gupta",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Punit.Gupta@sot.pdpu.ac.in",    "photo": "images/faculty/punitgupta.jpeg",    "qualification": "Ph.D",
    "cabin": "F 105",
    "phdSubject": "Cloud Computing Trust Management",
    "college": "Jaypee University of Information Technology",
    "researchInterest": "Cloud Computing",
    "phone": "98822 05191",
    "timetable": "images/faculty/punittt.jpeg"
  },
  {
    "id": 17,
    "name": "Dr. Rajeev Gupta",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Rajeev.Gupta@sot.pdpu.ac.in",
    "photo": "images/faculty/rajeevgupta.jpeg",
    "qualification": "Ph.D",
    "phdSubject": "Computer Science & Engineering",
    "college": "MANIT Bhopal",
    "researchInterest": "ML, DL & AI",
    "phone": "98939 44156",
    "cabin": "F block 1st floor Cubical",
    "timetable": "images/faculty/rajeevtt.jpeg"
  },
  {
    "id": 18,
    "name": "Dr. Riddhi Thakkar",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Riddhi.Thakkar@sot.pdpu.ac.in",
    "photo": "images/faculty/riddhithakkar.jpeg",
    "qualification": "Ph.D",
    "phdSubject": "Computer Science & Engineering",
    "college": "",
    "researchInterest": "",
    "cabin": "F 305",
    "timetable": "images/faculty/riddhitt.jpeg"
  },
  {
    "id": 19,
    "name": "Dr. Rutvij H Jhaveri",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Rutvij.Jhaveri@sot.pdpu.ac.in",
    "photo": "images/faculty/rutvijjhaveri.jpeg",
    "qualification": "Ph.D, M.Tech, B.E.",
    "phdSubject": "Software Defined Networking",
    "college": "Nirma University",
    "researchInterest": "Software Defined Networking",
    "cabin": "E 209-2",
    "timetable": "images/faculty/rutvijtt.jpeg"
  },
  {
    "id": 20,
    "name": "Dr. Shilpa Pandey",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Shilpa.Pandey@sot.pdpu.ac.in",
    "photo": "images/faculty/shilpapandey.jpeg",
    "qualification": "Ph.D, M.Tech, B.Tech",
    "phdSubject": "Computer Vision & Machine Learning",
    "college": "IIT Jodhpur",
    "researchInterest": "Deep Learning",
    "phone": "77909 15175",
    "cabin": "E 213",
    "timetable": "images/faculty/shilpatt.jpeg"
  },
  {
    "id": 21,
    "name": "Dr. Sidheswar Routray",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Sidheswar.Routray@sot.pdpu.ac.in",
    "photo": "images/faculty/sideshwarroutray.jpeg",
    "qualification": "Ph.D, M.Tech",
    "phdSubject": "Artificial Intelligence",
    "college": "KIIT University",
    "researchInterest": "AI, Machine Learning",
    "phone": "98615 95680",
    "cabin": "F 105",
    "timetable": "images/faculty/sideshwartt.jpeg"
  },
  {
    "id": 22,
    "name": "Dr. Tanmay Bhowmik",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Tanmay.Bhowmik@sot.pdpu.ac.in",
    "photo": "images/faculty/tanmaybhaumik.jpeg",
    "qualification": "Ph.D",
    "phdSubject": "Speech Processing",
    "college": "IIT Kharagpur",
    "researchInterest": "Speech Processing",
    "phone": "94764 09727",
    "cabin": "F block 1st floor Cubical",
    "timetable": "images/faculty/tanmaytt.jpeg"
  },
  {
    "id": 23,
    "name": "Dr. Trishna Paul",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Trishna.Paul@sot.pdpu.ac.in",
    "photo": "images/faculty/trishnapaul.jpeg",
    "qualification": "Ph.D",
    "phdSubject": "Computer Science & Engineering",
    "college": "BITS Pilani",
    "researchInterest": "AI & ML",
    "phone": "70632 29292",
    "cabin": "F 305",
    "timetable": "images/faculty/trishnatt.jpeg"
  },
  {
    "id": 24,
    "name": "Dr. Utkarsh Tiwari",
    "designation": "Assistant Professor",
    "department": "Department of Computer Science and Engineering, School of Technology",
    "email": "Utkarsh.Tiwari@sot.pdpu.ac.in",
    "photo": "images/faculty/utkarshtiwari.jpeg",
    "qualification": "Ph.D, M.Tech, B.E.",
    "phdSubject": "Hardware Security",
    "college": "IIIT Naya Raipur",
    "researchInterest": "Cryptography & Hardware Security",
    "phone": "90981 59815",
    "cabin": "E block 2nd floor Cubical",
    "timetable": "images/faculty/utkashtt.jpeg"
  }
];
